'use client';
import {ThemeToggle} from './theme-provider';
import {useState} from 'react';
import {ArrowRight,Waves,ShieldCheck,Smartphone,Mail} from 'lucide-react';
export async function api(path:string,data?:unknown){const res=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined,cache:'no-store'});const b:any=await res.json();if(!res.ok)throw new Error(b.error||'Request failed');return b}
export default function AuthPanel({onLogin}: {setup:boolean;setupEmail:string|null;onLogin:()=>void}){const [mode,setMode]=useState('login');const [error,setError]=useState(()=>typeof window!=='undefined'?new URLSearchParams(window.location.search).get('auth_error')||'':'');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');try{const data=Object.fromEntries(new FormData(e.currentTarget));const invitation=new URLSearchParams(window.location.search).get('invite');const result=await api('/api/auth',{...data,action:mode,...(mode==='register'&&invitation?{invite:invitation}:{})});if(result.message)setMessage(result.message);else onLogin()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <main className="auth-page"><section className="auth-story"><div className="brand"><Waves/><span>personal insider<span className="brand-small">W MALDIVES · GUEST RELATIONS</span></span></div><div><p className="eyebrow">EVERY STAY, PERSONALLY CARED FOR</p><h1>A little more<br/>{' '}personal.<br/><em>Every day.</em></h1><p className="story-copy">Your guests, their moments, and everything that makes a stay extraordinary. All in one place.</p></div><div className="story-footer"><span>Fesdu Island, Maldives</span><span>04°00′ N · 72°49′ E</span></div></section><section className="auth-form"><div className="auth-box"><div className="auth-theme"><ThemeToggle/></div><p className="eyebrow">YOUR DAILY INSIDER</p><h2>{mode==='login'?'Welcome back.':mode==='reset'?'Let’s get you back in.':'Make yourself at home.'}</h2><p className="muted">{mode==='login'?'Sign in to your guest relations workspace.':mode==='reset'?'We’ll send a password-reset link to your email.':'Create your account to join the hotel’s guest relations workspace.'}</p><form onSubmit={submit} key={mode}>{mode==='register'&&<label>Your name<input name="name" autoComplete="name" required maxLength={100}/></label>}<label>Email address<input name="email" type="email" autoComplete="username" maxLength={254} required placeholder="you@example.com"/></label>{mode!=='reset'&&<label>Password<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={12} maxLength={128} required placeholder="At least 12 characters"/></label>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="guest-summary" role="status"><Mail size={18}/>{message}</p>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='reset'?'Send reset link':'Create account'}<ArrowRight size={18}/></button></form><div className="auth-links"><button className="text-button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setMessage('')}}>{mode==='login'?'New here? Create an account':'Already have an account? Sign in'}</button>{mode==='login'&&<button className="text-button" onClick={()=>{setMode('reset');setError('')}}>Forgot password?</button>}</div><div className="privacy-line"><ShieldCheck size={17}/> Private workspace <span>·</span><Smartphone size={17}/> Ready for your phone</div></div></section></main>}

