'use client';
import {useCallback,useEffect,useState} from 'react';
import {Waves,LayoutDashboard,PlaneLanding,House,ArrowLeftRight,PlaneTakeoff,Users,Archive,Settings,Plus,Search,ArrowUpRight,ChevronRight,Sparkles,CalendarDays,Clock,RefreshCw,LogOut,ShieldCheck,Download,Menu,NotebookPen} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Choice} from './controls';
import {api} from './auth-panel';
import Forms,{type Editor} from './forms';
import TeamSettings from './team-settings';
import {statuses,guestIn,sortGuests,sortMoves,matchesGuest,resortClock,displayDate,archived,type Guest,type Move,type RoomHistory,type User} from '@/lib/domain';
const nav=[['Dashboard',LayoutDashboard],['Arrivals',PlaneLanding],['In-House',House],['Room Moves',ArrowLeftRight],['Departures',PlaneTakeoff],['Guests',Users],['Archive',Archive],['Settings',Settings]] as const;
const sections=['Arrivals','In-House','Departures','Room Moves'];
const initials=(s:string)=>s.split(' ').slice(0,2).map(s=>s[0]).join('').toUpperCase();
function Badge({value}:{value:string}){return <span className={'badge status-'+value.toLowerCase().replaceAll(' ','-')}>{value}</span>}
export default function Dashboard({user,onLogout}:{user:User;onLogout:()=>void}){const [view,setView]=useState('Dashboard');const [tab,setTab]=useState('Arrivals');const [q,setQ]=useState('');const [data,setData]=useState<{guests:Guest[];moves:Move[];history:RoomHistory[]}>({guests:[],moves:[],history:[]});const [clock,setClock]=useState(()=>resortClock());const today=clock.date;const time=clock.time;const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [editor,setEditor]=useState<Editor|null>(null);const [profile,setProfile]=useState<string|null>(null);const [archiveGuest,setArchiveGuest]=useState<Guest|null>(null);const [busy,setBusy]=useState(false);const [synced,setSynced]=useState('');const [online,setOnline]=useState(true);
const canEdit=['Admin','Guest Relations'].includes(user.role);
const refresh=useCallback(async()=>{try{const d=await api('/api/data');setData(d);setClock(resortClock());setError('');setSynced(new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Indian/Maldives'}))}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
useEffect(()=>{
 const tick=()=>{const next=resortClock();setClock(previous=>previous.date===next.date&&previous.time===next.time?previous:next)};
 const resume=()=>{tick();setOnline(navigator.onLine);if(navigator.onLine&&document.visibilityState==='visible')refresh()};
 resume();
 const clockTimer=setInterval(tick,1000);
 const pollTimer=setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine)refresh()},30000);
 window.addEventListener('online',resume);window.addEventListener('offline',resume);window.addEventListener('focus',resume);document.addEventListener('visibilitychange',resume);
 return()=>{clearInterval(clockTimer);clearInterval(pollTimer);window.removeEventListener('online',resume);window.removeEventListener('offline',resume);window.removeEventListener('focus',resume);document.removeEventListener('visibilitychange',resume)};
},[refresh]);
useEffect(()=>{const navigate=()=>{const v=decodeURIComponent(location.hash.slice(1));if(nav.some(n=>n[0]===v))setView(v)};navigate();window.addEventListener('hashchange',navigate);return()=>window.removeEventListener('hashchange',navigate)},[]);
function go(v:string){setView(v);setQ('');window.scrollTo({top:0});location.hash=encodeURIComponent(v)}
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'navigate_guest_view',description:'Navigate to a guest relations view. Does not change guest records.',inputSchema:{type:'object',properties:{view:{type:'string',enum:nav.map(n=>n[0])}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(!nav.some(n=>n[0]===input?.view))throw new Error('Invalid view');go(input.view);return {view:input.view}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
const active=data.guests.filter(g=>!archived(g,today,time));const current=profile?data.guests.find(g=>g.id===profile):null;
const pendingMoves=data.moves.filter(m=>!['Done','Cancelled'].includes(m.status)&&active.some(g=>g.id===m.guest_id)).sort(sortMoves);
const counts=[active.filter(g=>g.arrival===today).length,active.filter(g=>g.arrival<=today).length,active.filter(g=>g.departure===today).length,pendingMoves.filter(m=>m.move_date===today).length];
const section=view==='Dashboard'?tab:view;
const filtered=data.guests.filter(g=>guestIn(g,section,today,time)&&matchesGuest(g,q,data.moves,data.history)).sort((a,b)=>sortGuests(a,b,section));
const filteredMoves=pendingMoves.filter(m=>{const g=data.guests.find(g=>g.id===m.guest_id);return g&&matchesGuest(g,q,data.moves,data.history)});
async function mutate(payload:unknown,message:string){setBusy(true);try{await api('/api/data',payload);await refresh();toast.success(message);return true}catch(e){toast.error((e as Error).message);return false}finally{setBusy(false)}}
async function logout(){try{await api('/api/auth',{action:'logout'});setData({guests:[],moves:[],history:[]});onLogout()}catch(e){toast.error((e as Error).message)}}
function roomMoveText(g:Guest){const m=pendingMoves.find(m=>m.guest_id===g.id);return m?'→ '+m.new_room+' · '+displayDate(m.move_date):g.move_planned?'To be planned':'—'}
function GuestRows({items,compact=false}:{items:Guest[];compact?:boolean}){return <><div className="desktop-table"><Table><TableHeader><TableRow><TableHead>Room</TableHead><TableHead>Guest</TableHead>{section==='Departures'?<><TableHead>Checkout date</TableHead><TableHead>Time</TableHead></>:<><TableHead>Arrival</TableHead><TableHead>Departure</TableHead></>}<TableHead>Marriott</TableHead>{!compact&&section!=='Departures'&&<><TableHead>Travel agent</TableHead><TableHead>Celebration</TableHead><TableHead>EPIC moment</TableHead><TableHead>Room move</TableHead></>}<TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{items.map(g=><TableRow key={g.id}><TableCell><button className="room-number" onClick={()=>setProfile(g.id)}>{g.room}</button></TableCell><TableCell><button className="guest-name" onClick={()=>setProfile(g.id)}><span className="avatar">{initials(g.name)}</span><span>{g.name}{compact&&<small>{g.celebration!=='None'?g.celebration:g.travel_agent||g.meal_plan}</small>}</span></button></TableCell>{section==='Departures'?<><TableCell>{displayDate(g.departure)}</TableCell><TableCell>{g.checkout_time||'Not set'}</TableCell></>:<><TableCell>{displayDate(g.arrival)}{g.arrival===today&&<small className="today-tag">Today</small>}</TableCell><TableCell>{displayDate(g.departure)}</TableCell></>}<TableCell><span className="membership">{g.membership}</span></TableCell>{!compact&&section!=='Departures'&&<><TableCell>{g.travel_agent||'—'}</TableCell><TableCell>{g.celebration}</TableCell><TableCell className="wrap-cell">{g.epic||'—'}{g.epic&&<small>EPIC · {g.epic_status}</small>}</TableCell><TableCell>{roomMoveText(g)}</TableCell></>}<TableCell>{canEdit?<Choice label={'Status for '+g.name} value={g.status} options={statuses} disabled={busy} onChange={v=>mutate({action:'status',guest_id:g.id,version:g.version,status:v},'Status updated')}/>:<Badge value={g.status}/>}</TableCell></TableRow>)}</TableBody></Table></div><div className="mobile-guests">{items.map(g=><article className="mobile-guest" key={g.id}><button className="mobile-guest-main" onClick={()=>setProfile(g.id)}><span className="avatar">{initials(g.name)}</span><span><strong>{g.name}</strong><small>Room {g.room} · {g.membership}</small></span><ChevronRight size={18}/></button><div className="mobile-dates"><span>{displayDate(g.arrival)} → {displayDate(g.departure)}</span>{g.celebration!=='None'&&<span>{g.celebration}</span>}{section==='Departures'&&<strong>{g.checkout_time||'Time not set'}</strong>}</div><div className="mobile-status">{canEdit?<Choice label={'Status for '+g.name} value={g.status} options={statuses} disabled={busy} onChange={v=>mutate({action:'status',guest_id:g.id,version:g.version,status:v},'Status updated')}/>:<Badge value={g.status}/>}<button className="text-button" onClick={()=>setProfile(g.id)}>Guest details<ChevronRight size={15}/></button></div></article>)}</div></>}
function MoveList({items}:{items:Move[]}){return <div className="move-list">{items.map(m=>{const g=data.guests.find(g=>g.id===m.guest_id);return <article className="move-card" key={m.id}><div className="move-clock"><strong>{m.move_time}</strong><span>{displayDate(m.move_date)}</span>{m.move_date<today&&<span className="overdue">Overdue</span>}</div><div className="move-detail"><button className="guest-name" onClick={()=>setProfile(m.guest_id)}>{g?.name}</button><p><strong>{m.old_room}</strong><ArrowLeftRight size={16}/><strong>{m.new_room}</strong><span className="membership">{g?.membership}</span></p><span className="muted">{m.reason}</span></div><div className="move-actions">{canEdit?<><Choice label={'Move status for '+g?.name} value={m.status} options={statuses} disabled={busy} onChange={s=>mutate({action:'move-status',guest_id:m.guest_id,move_id:m.id,version:m.version,status:s},s==='Done'?'Room updated and history saved':'Move updated')}/><button className="text-button" onClick={()=>setEditor({kind:'move',guest:g,move:m})}>Edit move</button></>:<Badge value={m.status}/>}</div></article>})}</div>}
return <SidebarProvider style={{'--sidebar-width':'236px'} as React.CSSProperties}><Sidebar><SidebarHeader className="sidebar-brand"><div className="brand"><Waves/><span>personal<br/>insider<span className="brand-small">W MALDIVES</span></span></div></SidebarHeader><SidebarContent className="sidebar-nav"><p className="eyebrow">YOUR WORKSPACE</p><SidebarMenu>{nav.map(([name,Icon])=><SidebarMenuItem key={name}><SidebarMenuButton isActive={view===name} onClick={()=>go(name)} className="nav-button"><Icon/><span>{name}</span>{name==='In-House'&&<span className="nav-count">{counts[1]}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="island-note"><Waves size={25}/><p>Small details.<br/><strong>Extraordinary stays.</strong></p><span>GUEST RELATIONS · MALDIVES</span></div></SidebarContent><SidebarFooter><div className="user-block"><span className="avatar">{initials(user.name)}</span><span><strong>{user.name}</strong><small>{user.role}</small></span><button className="icon-button" aria-label="Log out" onClick={logout}><LogOut size={17}/></button></div></SidebarFooter></Sidebar>
<div className="workspace"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger/><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="topbar-right"><ShieldCheck size={16}/><span>Private workspace</span><span className="avatar small-avatar">{initials(user.name)}</span></div></header><main className="main-content"><div className="page-heading"><div><p className="eyebrow">{view==='Dashboard'?'YOUR DAY, AT A GLANCE':'GUEST RELATIONS'}</p><h1>{view==='Dashboard'?'Today':view}<span className="heading-dot">.</span></h1><p className="muted">{view==='Dashboard'?new Date(today+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):view==='Archive'?'Past stays, safely kept for the next welcome.':view==='Settings'?'Your account, your team, and your mobile workspace.':'Every guest detail, always connected.'}</p></div>{canEdit&&view!=='Settings'&&<button className="primary add-guest" onClick={()=>setEditor({kind:'guest'})}><Plus size={19}/>Add Guest</button>}</div>
{(!online||error)&&<div className="error" role="alert">{!online?'You are offline. Connect to view the latest guest information and save changes.':error}<button className="text-button" onClick={refresh}>Retry</button></div>}
{view==='Dashboard'&&<div className="stats">{sections.map((s,i)=>{const Icon=[PlaneLanding,House,PlaneTakeoff,ArrowLeftRight][i];return <button className={'stat stat-'+i+(tab===s?' selected':'')} key={s} onClick={()=>setTab(s)} aria-pressed={tab===s}><span className="stat-label"><span className="stat-icon"><Icon size={19}/></span>{s}<ArrowUpRight size={16}/></span><strong>{String(counts[i]).padStart(2,'0')}</strong><span>{i===0?'Welcomes today':i===1?'Guests staying today':i===2?'Farewells today':'Scheduled today'}</span></button>})}</div>}
{view==='Settings'?<TeamSettings user={user}/>:<div className={view==='Dashboard'?'dashboard-grid':'single-grid'}><section className="guest-panel"><div className="panel-title"><div><h2>{view==='Dashboard'?'The guest list':view==='Guests'?'All active guests':view==='Archive'?'Guest history':view}</h2><p>{view==='Dashboard'?'Everything you need for a thoughtful welcome.':section==='Arrivals'?'Today and upcoming arrivals, in order.':section==='Room Moves'?'Upcoming and outstanding room moves.':filtered.length+' guest'+(filtered.length===1?'':'s')}</p></div><button className="icon-button" aria-label="Refresh guests" onClick={refresh}><RefreshCw size={17}/></button></div>{view==='Dashboard'&&<Tabs value={tab} onValueChange={setTab}><TabsList className="guest-tabs">{sections.map(s=><TabsTrigger key={s} value={s}>{s}</TabsTrigger>)}</TabsList></Tabs>}
<div className="table-tools"><div className="search-box"><Search size={18}/><input aria-label="Search guests" placeholder="Search guests, rooms, membership, agents…" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button className="text-button" onClick={()=>setQ('')}>Clear</button>}</div>{canEdit&&<div className="quick-actions"><button className="secondary" onClick={()=>setEditor({kind:'move'})}><Plus size={16}/>Room Move</button><button className="secondary" onClick={()=>setEditor({kind:'departure'})}><Plus size={16}/>Departure</button></div>}</div>
{loading?<div className="empty-state" role="status">Loading your guest list…</div>:section==='Room Moves'?(filteredMoves.length?<MoveList items={filteredMoves}/>:<div className="empty-state"><ArrowLeftRight/><h3>No room moves {q?'match your search':'planned'}</h3><p>{q?'Try another name or room.':'Plan a move using an existing guest record.'}</p>{canEdit&&!q&&<button className="secondary" onClick={()=>setEditor({kind:'move'})}><Plus size={17}/>Room Move</button>}</div>):filtered.length?<>{section==='Arrivals'?<>{filtered.some(g=>g.arrival===today)&&<><div className="list-divider">TODAY · {displayDate(today)}</div><GuestRows items={filtered.filter(g=>g.arrival===today)} compact={view==='Dashboard'}/></>}{filtered.some(g=>g.arrival>today)&&<><div className="list-divider">UPCOMING ARRIVALS</div><GuestRows items={filtered.filter(g=>g.arrival>today)} compact={view==='Dashboard'}/></>}</>:<GuestRows items={filtered} compact={view==='Dashboard'}/>}</>:<div className="empty-state"><Users/><h3>{q?'No matching guests':section==='Archive'?'No archived stays yet':'A little room for your next guest.'}</h3><p>{q?'Search another name, room, membership, or travel agent.':section==='Archive'?'Past departures will appear here automatically.':'Add a guest once. Their stay will appear in the right daily views.'}</p>{canEdit&&!q&&section!=='Archive'&&<button className="primary" onClick={()=>setEditor({kind:'guest'})}><Plus size={17}/>Add your first guest</button>}</div>}
<div className="panel-footer"><span><ShieldCheck size={14}/> Securely saved online</span><span>{synced?'Updated '+synced+' MVT':'Maldives time'}</span></div></section>{view==='Dashboard'&&<aside className="attention-column"><section className="attention-card"><div className="attention-heading"><Sparkles size={20}/><h2>A little extra care</h2></div><p className="muted">Moments to make memorable today.</p>{active.filter(g=>g.arrival<=today&&(g.celebration!=='None'||g.epic)).slice(0,5).map(g=><button className="moment" key={g.id} onClick={()=>setProfile(g.id)}><span className="moment-room">{g.room}</span><span><strong>{g.name}</strong><small>{g.celebration!=='None'?g.celebration:g.epic}</small></span><ChevronRight size={15}/></button>)}{!active.some(g=>g.arrival<=today&&(g.celebration!=='None'||g.epic))&&<div className="quiet-note">Celebrations and EPIC moments for in-house guests will appear here.</div>}</section><section className="attention-card"><div className="attention-heading"><Clock size={19}/><h2>Needs attention</h2></div>{active.filter(g=>g.arrival<=today&&['Pending','In Progress'].includes(g.status)).slice(0,5).map(g=><button className="attention-item" key={g.id} onClick={()=>setProfile(g.id)}><span><strong>{g.name}</strong><small>Room {g.room}</small></span><Badge value={g.status}/></button>)}{!active.some(g=>g.arrival<=today&&['Pending','In Progress'].includes(g.status))&&<p className="quiet-note">You’re all caught up on active guest requests.</p>}</section><div className="daily-note"><CalendarDays size={19}/><p>Always on island time.<span>Arrivals update at midnight Maldives time. Stays archive at checkout time, or at midnight after departure if no time is set.</span></p></div></aside>}</div>}</main><nav className="mobile-nav" aria-label="Mobile navigation">{[['Dashboard',LayoutDashboard],['Guests',Users],['Room Moves',ArrowLeftRight],['Settings',Settings]].map(([name,I])=>{const Icon=I as typeof Users;return <button key={name as string} onClick={()=>go(name as string)} className={view===name?'active':''}><Icon size={21}/><span>{name as string==='Dashboard'?'Today':name as string==='Room Moves'?'Moves':name as string}</span></button>})}</nav></div>
{editor&&<Forms editor={editor} guests={data.guests} onClose={()=>setEditor(null)} onSaved={async()=>{await refresh();toast.success('Saved successfully')}}/>}
<Sheet open={!!current} onOpenChange={o=>!o&&setProfile(null)}><SheetContent className="profile-sheet"><SheetHeader><p className="eyebrow">GUEST PROFILE</p><SheetTitle>{current?.name}</SheetTitle><SheetDescription>Every detail, throughout their stay.</SheetDescription></SheetHeader>{current&&<div className="profile-body"><div className="profile-room"><span>ROOM<strong>{current.room}</strong></span><Badge value={current.status}/></div><div className="profile-grid">{[['Arrival',displayDate(current.arrival)],['Departure',displayDate(current.departure)],['Checkout',current.checkout_time||'Not set'],['Meal plan',current.meal_plan||'—'],['Marriott',current.membership],['Travel agent',current.travel_agent||'—'],['Celebration',current.celebration],['Room move',roomMoveText(current)]].map(([l,v])=><div key={l}><small>{l}</small><strong>{v}</strong></div>)}</div>{canEdit&&<div className="profile-actions"><button className="primary" onClick={()=>setEditor({kind:'guest',guest:current})}><NotebookPen size={17}/>Edit guest</button><button className="secondary" onClick={()=>setEditor({kind:'departure',guest:current})}>Departure</button></div>}<section><h3><Sparkles size={18}/>EPIC moment</h3><p className="preserve">{current.epic||'No EPIC moment added yet.'}</p><p>EPIC status: <Badge value={current.epic_status}/></p></section><section><h3>Feedback</h3><p className="preserve">{current.feedback||'No feedback added yet.'}</p></section><section><h3>Notes</h3><p className="preserve">{current.notes||'No notes yet.'}</p></section><section><div className="panel-title"><h3>Room moves</h3>{canEdit&&!archived(current,today,time)&&<button className="text-button" onClick={()=>setEditor({kind:'move',guest:current})}>+ Plan move</button>}</div><MoveList items={pendingMoves.filter(m=>m.guest_id===current.id)}/></section><section><h3>Room move history</h3>{data.history.filter(h=>h.guest_id===current.id).map(h=><div className="history-entry" key={h.id}><strong>{h.old_room} → {h.new_room}</strong><small>{new Date(h.changed_at).toLocaleString('en-GB',{timeZone:'Indian/Maldives',dateStyle:'medium',timeStyle:'short'})} MVT</small><p>{h.reason}</p></div>)}{!data.history.some(h=>h.guest_id===current.id)&&<p className="muted">No room changes yet.</p>}{data.moves.filter(m=>m.guest_id===current.id&&m.status==='Cancelled').map(m=><div className="history-entry" key={m.id}><strong>{m.old_room} → {m.new_room} · Cancelled</strong><small>{displayDate(m.move_date)} · {m.move_time}</small><p>{m.reason}</p></div>)}</section>{canEdit&&(current.archived?<button className="secondary" disabled={busy} onClick={()=>mutate({action:'restore',guest_id:current.id,version:current.version},'Manual archive removed. Past stays remain in History.')}>Restore guest</button>:<button className="archive-button" onClick={()=>setArchiveGuest(current)}><Archive size={17}/>Archive guest</button>)}</div>}</SheetContent></Sheet>
<AlertDialog open={!!archiveGuest} onOpenChange={o=>!o&&setArchiveGuest(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Archive {archiveGuest?.name}?</AlertDialogTitle><AlertDialogDescription>Remove this guest from the active dashboard? Their details and room history will remain in Archive.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep guest</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{if(archiveGuest&&await mutate({action:'archive',guest_id:archiveGuest.id,version:archiveGuest.version},'Guest archived')){setArchiveGuest(null);setProfile(null)}}}>Archive guest</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster position="top-center" richColors/></SidebarProvider>}


