'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Choice,GuestPicker} from './controls';
import {api} from './auth-panel';
import {statuses,mealPlans,epicStatuses,memberships,celebrations,type Guest,type Move,resortToday,archived} from '@/lib/domain';
export type Editor={kind:'guest'|'move'|'departure';guest?:Guest;move?:Move};
export default function Forms({editor,guests,onClose,onSaved}:{editor:Editor;guests:Guest[];onClose:()=>void;onSaved:()=>Promise<void>}){const today=resortToday();const initial=editor.guest;const [selected,setSelected]=useState(initial?.id||'');const guest=guests.find(g=>g.id===selected);const [form,setForm]=useState<any>(editor.kind==='guest'?{name:'',room:'',meal_plan:'Breakfast only',membership:'None',arrival:today,departure:today,travel_agent:'',celebration:'None',epic:'',epic_status:'Pending',feedback:'',status:'Pending',move_planned:false,checkout_time:'',notes:'',...initial}:editor.kind==='move'?{new_room:'',move_date:today,move_time:'14:00',reason:'',...editor.move}:{departure:initial?.departure||today,checkout_time:initial?.checkout_time||'12:00',status:initial?.status||'Pending',notes:initial?.notes||''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
function set(k:string,v:unknown){setForm((f:any)=>({...f,[k]:v}))}
function selectGuest(id:string){setSelected(id);const g=guests.find(g=>g.id===id);if(g&&editor.kind==='departure')setForm({departure:g.departure,checkout_time:g.checkout_time||'12:00',status:g.status,notes:g.notes})}
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(editor.kind!=='guest'&&!guest)throw new Error('Select an existing guest first');await api('/api/data',editor.kind==='guest'?{action:'guest',guest:form}:editor.kind==='move'?{action:'move',guest_id:selected,move:form}:{action:'departure',guest_id:selected,version:guest!.version,...form});await onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function field(label:string,key:string,type='text',required=false){return <label key={key}>{label}<input type={type} value={form[key]||''} onChange={e=>set(key,e.target.value)} required={required} maxLength={type==='text'?key==='name'?160:key==='epic'?1000:160:undefined}/></label>}
function choice(label:string,key:string,options:readonly string[]){return <div className="field"><label>{label}</label><Choice label={label} value={form[key]} onChange={v=>set(key,v)} options={options}/></div>}
return <Dialog open onOpenChange={o=>{if(!o&&!busy)onClose()}}><DialogContent className="editor-dialog"><DialogHeader><p className="eyebrow">PERSONAL INSIDER</p><DialogTitle>{editor.kind==='guest'?(initial?'Edit guest':'Add a guest'):editor.kind==='move'?(editor.move?'Edit room move':'Plan a room move'):'Confirm departure'}</DialogTitle><DialogDescription>{editor.kind==='guest'?'One guest record, connected throughout their stay.':'Choose an existing guest. Their details stay connected.'}</DialogDescription></DialogHeader><form onSubmit={submit}>{editor.kind!=='guest'&&<><div className="field"><label>Select guest</label><GuestPicker guests={guests.filter(g=>!archived(g,today))} value={selected} onChange={selectGuest}/></div>{guest&&<div className="guest-summary"><strong>{guest.name}</strong><span>Room {guest.room} · {guest.membership}</span><span>{guest.arrival} → {guest.departure}</span></div>}</>}
<div className="form-grid">{editor.kind==='guest'?<>{field('Guest name','name','text',true)}{field('Room number','room','text',true)}{field('Arrival date','arrival','date',true)}{field('Departure date','departure','date',true)}{choice('Meal plan','meal_plan',mealPlans)}{choice('Marriott membership','membership',memberships)}{field('Travel agent','travel_agent')}{choice('Celebration','celebration',celebrations)}{choice('Status','status',statuses)}{field('Checkout time','checkout_time','time')}<div className="full">{field('EPIC moment','epic')}</div><div className="full">{choice('EPIC status','epic_status',epicStatuses)}</div><label className="full">Feedback<textarea value={form.feedback||''} onChange={e=>set('feedback',e.target.value)} maxLength={6000} placeholder="Guest feedback about their stay…"/></label><div className="switch-line full"><label htmlFor="move-planned">Room move planned?</label><Switch id="move-planned" checked={Boolean(form.move_planned)} onCheckedChange={v=>set('move_planned',v)}/></div>{form.move_planned&&<p className="form-hint full">Save this guest, then use + Room Move to set the new room and schedule.</p>}</>:editor.kind==='move'?<>{field('New room','new_room','text',true)}{field('Move date','move_date','date',true)}{field('Move time','move_time','time',true)}<div className="full">{field('Reason','reason','text',true)}</div><p className="form-hint full">The current room changes when you mark this move Done. Previous rooms remain in the guest’s history.</p></>:<>{field('Checkout date','departure','date',true)}{field('Checkout time','checkout_time','time',true)}{choice('Status','status',statuses)}</>}{editor.kind!=='move'&&<label className="full">Notes<textarea value={form.notes} onChange={e=>set('notes',e.target.value)} maxLength={6000} placeholder="Preferences, requests, and things to remember…"/></label>}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':editor.kind==='guest'?'Save guest':editor.kind==='move'?'Save room move':'Save departure'}</button></div></form></DialogContent></Dialog>}

