import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),password:text('password').notNull(),recovery:text('recovery').notNull(),role:text('role').notNull(),active:integer('active').notNull().default(1)});
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),user_id:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()});
export const invitations=sqliteTable('invitations',{token:text('token').primaryKey(),email:text('email').notNull(),role:text('role').notNull(),expires:integer('expires').notNull(),used_by:text('used_by').references(()=>users.id)});
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const guests=sqliteTable('guests',{id:text('id').primaryKey(),name:text('name').notNull(),room:text('room').notNull(),meal_plan:text('meal_plan').notNull(),membership:text('membership').notNull(),arrival:text('arrival').notNull(),departure:text('departure').notNull(),travel_agent:text('travel_agent').notNull().default(''),celebration:text('celebration').notNull(),epic:text('epic').notNull().default(''),status:text('status').notNull(),move_planned:integer('move_planned').notNull().default(0),checkout_time:text('checkout_time').notNull().default(''),notes:text('notes').notNull().default(''),archived:integer('archived').notNull().default(0),version:integer('version').notNull().default(1),created_at:text('created_at').notNull(),room_reason:text('room_reason').notNull().default('Room updated in guest profile'),room_changed_at:text('room_changed_at').notNull().default('')},t=>[index('idx_guests_departure_arrival').on(t.departure,t.arrival)]);
export const moves=sqliteTable('moves',{id:text('id').primaryKey(),guest_id:text('guest_id').notNull().references(()=>guests.id),old_room:text('old_room').notNull(),new_room:text('new_room').notNull(),move_date:text('move_date').notNull(),move_time:text('move_time').notNull(),reason:text('reason').notNull(),status:text('status').notNull().default('Pending'),version:integer('version').notNull().default(1)},t=>[index('idx_moves_guest').on(t.guest_id),index('idx_moves_schedule').on(t.move_date,t.move_time)]);
export const roomHistory=sqliteTable('room_history',{id:integer('id').primaryKey({autoIncrement:true}),guest_id:text('guest_id').notNull().references(()=>guests.id),old_room:text('old_room').notNull(),new_room:text('new_room').notNull(),changed_at:text('changed_at').notNull(),reason:text('reason').notNull()},t=>[index('idx_history_guest').on(t.guest_id)]);

